<?php
$this->headTitle('Change Password');

//$this->mainMenu()->setActiveItemId('users');
//
//$this->pageBreadcrumbs()->setItems([
//    'Home'=>$this->url('home'),
//    'Manage Users'=>$this->url('users'),
//    'Change Password'=>$this->url('users', ['action'=>'change-password', 'id'=>$user->getId()])
//]);

$form->get('old_password')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'Enter old password'
]);

$form->get('new_password')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'Enter new password'
]);

$form->get('confirm_new_password')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'Re-enter new password'
]);

$form->get('submit')->setAttributes(['class'=>'btn btn-primary']);

$form->prepare();
?>

<div class="col-md-12">
    <h2>Edit User <?= $this->escapeHtml($user->getFullName()) ?></h2>
</div>
<div class="col-md-9">
    <div class="card card-info">
        <div class="card-header">
            <h3 class="card-title">Please fill out the following form and click the <i>Update</i> button.</h3>
        </div>
        <div class="card-body">
            <?= $this->form()->openTag($form); ?>

            <?= $this->formLabel($form->get('old_password')); ?>
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text"><i class="fas fa-user"></i></span>
                </div>
                <?= $this->formElement($form->get('old_password')); ?>
                <?= $this->formElementErrors($form->get('old_password')); ?>
            </div>

            <?= $this->formLabel($form->get('new_password')); ?>
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text"><i class="fas fa-user"></i></span>
                </div>
                <?= $this->formElement($form->get('new_password')); ?>
                <?= $this->formElementErrors($form->get('new_password')); ?>
            </div>

            <?= $this->formLabel($form->get('confirm_new_password')); ?>
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text"><i class="fas fa-user"></i></span>
                </div>
                <?= $this->formElement($form->get('confirm_new_password')); ?>

                <?= $this->formElementErrors($form->get('confirm_new_password')); ?>
            </div>
        </div>
        <!-- /.card-body -->
    </div>
</div>
<div class="col-md-3">
    <div class="card card-info">
        <div class="card-header">
            <h3 class="card-title">Settings</h3>
        </div>
        <div class="card-body">
<!--            --><?//= $this->formElement($form->get('csrf')); ?>
<!--            --><?//= $this->formElementErrors($form->get('csrf')); ?>

            <?= $this->formElement($form->get('submit')); ?>

            <?= $this->form()->closeTag(); ?>
        </div>
        <!-- /.card-body -->
    </div>
</div>


