
<?= $this->flashMessenger()->render('error', ['alert', 'alert-warning']); ?>
<?= $this->flashMessenger()->render('success', ['alert', 'alert-success']); ?>
<?= $this->flashMessenger()->render('info', ['alert', 'alert-info']); ?>
<hr>
<h1>Posts</h1>

<div class="row">

    <div class="col-md-8">

        <?php foreach($posts as $post): ?>

            <h3>
                <a href="<?= $this->url('posts', ['action'=>'view', 'id'=>$post->getId()]); ?>">
                    <?= $this->escapeHtml($post->getTitle()); ?>
                </a>
            </h3>

            <p>
                Published: <?= $this->escapeHtml(date('jS \of F Y', strtotime($post->getDateCreated()))); ?>
                | Tags: <?= $this->escapeHtml($postManager->convertTagsToString($post)); ?>
            </p>

            <p class="comments-header">
                <?= $this->escapeHtml($postManager->getCommentCountStr($post)); ?> |
                <a href="<?= $this->url('posts', ['action'=>'view', 'id'=>$post->getId()],
                    ['fragment'=>'comment']); ?>">
                    Add new comment
                </a>
            </p>

            <p>
                <?= $this->escapeHtml($post->getContent()); ?>
            </p>

        <?php endforeach; ?>

        <?= $this->paginationControl($posts, 'Sliding', 'user/partial/paginator', ['route' => 'posts']); ?>
    </div>

<!--    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Popular Tags</h3>
            </div>
            <div class="panel-body">
                <?php //foreach($this->tagCloud as $tagName => $frequency): ?>

                    <a href="<?php // $this->url('users', ['action'=>'index'], ['query'=>['tag'=>$tagName]]); ?>">

                    <span style="font-size:<?php //$frequency * 5?>em">
                        <?php // $this->escapeHtml($tagName); ?>
                    </span>

                    </a>

                <?php //endforeach; ?>
            </div>
        </div>
    </div>-->
</div>