version: '2.3'
services:
  php-fpm:
    container_name: php
    build:
      context: docker/php-fpm
    volumes:
      - ./:/code
    environment:
      XDEBUG_CONFIG: "remote_host=192.168.220.1 remote_enable=1"
      PHP_IDE_CONFIG: "serverName=Docker"
#    networks:
#      - internal
  nginx:
    container_name: nginx
    build:
      context: docker/nginx
    volumes:
      - ./:/code
    ports:
      - "8180:8180"
    depends_on:
      - php-fpm
#    networks:
#      - internal
  db:
    image: mysql:5.7
    container_name: mysql
    volumes:
      - ./mysql/etc/mysql:/etc/mysql
      - ./mysql/logs/mysql:/var/log/mysql
      - ./mysql:/var/lib/mysql
      - ./mysql/mysql-files:/var/lib/mysql-files
      - ./mysql/data:/docker-entrypoint-initdb.d
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laminas_blog
      MYSQL_USER: blog
      MYSQL_PASSWORD: blog
    ports:
      - "3206:3306"
  mongodb:
    image : mongo
    container_name: mongodb
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/web/mongodb/database:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped
  redis:
    build:
      context: docker/redis
    container_name: 'redis'
    restart: always
    ports:
      - "6379:6379"
