<?php
$this->headTitle('Edit Role Permissions');

//$this->mainMenu()->setActiveItemId('roles');
//
//$this->pageBreadcrumbs()->setItems([
//            'Home'=>$this->url('home'),
//            'Manage Roles'=>$this->url('roles'),
//            'Edit Role'=>$this->url('roles', ['action'=>'edit', 'id'=>$role->getId()])
//            ]);

$form->get('submit')
        ->setAttributes(['class'=>'btn btn-primary btn-block'])
        ->setValue('Save Permissions');

$form->prepare();
?>


<div class="col-md-12">
    <h2>Edit Permissions of <?= $this->escapeHtml($role->getName()) ?></b></h2>
</div>
<div class="col-md-7">
    <!-- About Me Box -->
    <div class="card card-primary">
        <div class="card-header">
            <h3 class="card-title"> Edit Permissions</h3>
        </div>
        <!-- /.card-header -->
        <div class="card-body">
            <?= $this->form()->openTag($form); ?>
            <table class="table table-striped table-bordered">
                <tr>
                    <th>Name</th>
                    <th>Description</th>
                </tr>
                <?php foreach ($allPermissions as $permission):
                    $element = $form->get('permissions')->get($permission->getName());
                    ?>
                    <tr>
                        <td>
                            <div class="checkbox">
                                <label><input type="checkbox" name="<?= $this->escapeHtmlAttr($element->getName()) ?>"
                                              value="<?= $this->escapeHtmlAttr($element->getCheckedValue()) ?>"
                                        <?php if ($element->isChecked()) echo 'checked'?>
                                        <?php if ($element->getAttribute('disabled')) echo 'disabled'?>>
                                    <?= $this->escapeHtml($element->getLabel()) ?>
                                </label>
                                <?= $this->formElementErrors($element); ?>
                            </div>
                        </td>
                        <td>
                            <?= $this->escapeHtml($permission->getDescription()) ?>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </table>
            <?= $this->formElement($form->get('csrf')); ?>


            <hr>
            <?= $this->formElement($form->get('submit')); ?>

            <?= $this->form()->closeTag(); ?>
        </div>
        <!-- /.card-body -->
    </div>
    <!-- /.card -->
</div>