<?php
$this->headTitle('Add Tag');

$form->get('post-tag-name')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'Enter name'
]);

$form->get('submit')->setAttributes(['class'=>'btn btn-primary form-control']);

$form->prepare();
?>

<div class="col-md-12">
    <h2>Add Category</h2>
</div>
<div class="col-md-9">
    <div class="card card-info">
        <div class="card-header">
            <h3 class="card-title">Please fill out the following form and click the <i>Create</i> button.</h3>
        </div>
        <div class="card-body">
            <?= $this->form()->openTag($form); ?>

            <?= $this->formLabel($form->get('post-tag-name')); ?>
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text"><i class="fas fa-user-secret"></i></span>
                </div>
                <?= $this->formElement($form->get('post-tag-name')); ?>
                <?= $this->formElementErrors($form->get('post-tag-name')); ?>
            </div>

        </div>
        <!-- /.card-body -->
    </div>
</div>
<div class="col-md-3">
    <div class="card card-info">
        <div class="card-header">
            <h3 class="card-title">Settings</h3>
        </div>
        <div class="card-body">

            <?= $this->formElement($form->get('csrf')); ?>
            <?= $this->formElementErrors($form->get('csrf')); ?>

            <?= $this->formElement($form->get('submit')); ?>

            <?= $this->form()->closeTag(); ?>
        </div>
        <!-- /.card-body -->
    </div>
</div>
