<?php
$this->headTitle('View Tag');

?>
<div class="col-md-12">
    <h2>View Role <b><?= $this->escapeHtml($tag->getName()) ?></b></h2>
</div>
<div class="col-md-5">
    <div class="card card-primary card-outline">
        <div class="card-body box-profile">

            <h3 class="profile-username text-center"> ID <?= $this->escapeHtml($tag->getId()) ?></h3>

            <p class="text-muted text-center"><?= $this->escapeHtml($tag->getName()) ?></p>


            <a href="<?= $this->url('posts-tags', ['action'=>'edit', 'id'=>$tag->getId()]); ?>"
               class="btn btn-primary btn-block"><b>Edit <?= $this->escapeHtml($tag->getName()) ?></b></a>
        </div>
        <!-- /.card-body -->
    </div>
    <!-- /.card -->
</div>
<div class="col-md-7">

</div>
