<?php
$this->headTitle('Sign in');

//$this->mainMenu()->setActiveItemId('login');

$form->get('email')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'Email address',
    'required' => true,
    'autofocus' => true
])
    ->setLabelAttributes([
        'class' => 'sr-only'
    ]);

$form->get('password')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'Password',
    'required' => true,
])
    ->setLabelAttributes([
        'class' => 'sr-only'
    ]);
?>

<!--    <div class="col-md-offset-4 col-md-4">-->
<!--        <form class="form-signin" method="post">-->
<!--            <h2 class="form-signin-heading">Please sign in</h2>-->
<!---->
<!--            --><?php //if ($isLoginError): ?>
<!--                <div class="alert alert-warning" role="alert">-->
<!--                    Incorrect login and/or password.-->
<!--                    <a href="--><?//= $this->url('reset-password') ?><!--">Forgot password?</a>-->
<!--                </div>-->
<!--            --><?php //endif; ?>
<!---->
<!--            --><?//= $this->formLabel($form->get('email')); ?>
<!--            --><?//= $this->formElement($form->get('email')); ?>
<!---->
<!--            --><?//= $this->formLabel($form->get('password')); ?>
<!--            --><?//= $this->formElement($form->get('password')); ?>
<!---->
<!--            <div class="checkbox">-->
<!--                <label>-->
<!--                    --><?//= $this->formElement($form->get('remember_me')); ?><!-- Remember me-->
<!--                </label>-->
<!--            </div>-->
<!---->
<!--            <br>--><?//= $recaptcha->getHTML(); ?><!--<br>-->
<!--            --><?//= $this->formElement($form->get('redirect_url')); ?>
<!--            --><?//= $this->formElement($form->get('csrf')) ?>
<!---->
<!--            <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>-->
<!--        </form>-->
<!--    </div>-->

<div class="login-box">
    <div class="login-logo">
        <a href="<?= $this->url('home') ?>"><b>Admin</b>LTE</a>
    </div>
    <!-- /.login-logo -->
    <div class="card">
        <div class="card-body login-card-body">
            <p class="login-box-msg">Sign in to start your session</p>
            <form class="form-signin" method="post">
            <?php if ($isLoginError): ?>
                <div class="alert alert-warning" role="alert">
                    Incorrect login and/or password.
                    <a href="<?= $this->url('reset-password') ?>">Forgot password?</a>
                </div>
            <?php endif; ?>
                <?= $this->formLabel($form->get('password')); ?>
                <div class="input-group mb-3">
                    <?= $this->formElement($form->get('email')); ?>
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="fas fa-envelope"></span>
                        </div>
                    </div>
                </div>

                <?= $this->formLabel($form->get('password')); ?>
                <div class="input-group mb-3">
                    <?= $this->formElement($form->get('password')); ?>
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="fas fa-lock"></span>
                        </div>
                    </div>
                </div>
                <?= $recaptcha->getHTML(); ?><br>
                <div class="row">
                    <div class="col-8">
                        <div class="icheck-primary">
                            <?= $this->formElement($form->get('remember_me')); ?>
                            <label for="remember">
                                Remember Me
                            </label>
                        </div>
                    </div>
                    <?= $this->formElement($form->get('redirect_url')); ?>
                    <?= $this->formElement($form->get('csrf')) ?>
                    <!-- /.col -->
                    <div class="col-4">
                        <button type="submit" class="btn btn-primary btn-block">Sign In</button>
                    </div>
                    <!-- /.col -->
                </div>
            </form>

<!--            <div class="social-auth-links text-center mb-3">-->
<!--                <p>- OR -</p>-->
<!--                <a href="#" class="btn btn-block btn-primary">-->
<!--                    <i class="fab fa-facebook mr-2"></i> Sign in using Facebook-->
<!--                </a>-->
<!--                <a href="#" class="btn btn-block btn-danger">-->
<!--                    <i class="fab fa-google-plus mr-2"></i> Sign in using Google+-->
<!--                </a>-->
<!--            </div>-->
            <!-- /.social-auth-links -->

            <p class="mb-1">
                <a href="<?= $this->url('reset-password') ?>">I forgot my password</a>
            </p>
            <p class="mb-0">
                <a href="<?= $this->url('registration') ?>" class="text-center">Register a new membership</a>
            </p>
        </div>
    </div>
</div>