<?php
$this->headTitle('Registration');

//$this->mainMenu()->setActiveItemId('login');
$form->get('full_name')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'Full Name',
    'required' => true,
])
    ->setLabelAttributes([
        'class' => 'sr-only'
    ]);

$form->get('email')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'Email address',
    'required' => true,
    'autofocus' => true
])
    ->setLabelAttributes([
        'class' => 'sr-only'
    ]);

$form->get('password')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'Password',
    'required' => true,
])
    ->setLabelAttributes([
        'class' => 'sr-only'
    ]);
$form->get('confirm_password')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'Confirm Password',
    'required' => true,
])
    ->setLabelAttributes([
        'class' => 'sr-only'
    ]);
?>
<!--<form class="form">-->
<!--    <div class="card-body">-->
<!--        <div class="form-group row">-->
<!--            <label class="col-sm-4 col-form-label">-->
<!--                --><?//= $this->formLabel($form->get('full_name')); ?>
<!--            </label>-->
<!--            <div class="col-sm-8">-->
<!--                --><?//= $this->formElement($form->get('full_name')); ?>
<!--            </div>-->
<!--        </div>-->
<!--    </div>-->
<!--     /.card-body -->
<!--    <div class="card-footer">-->
<!--        <button type="submit" class="btn btn-info form-control">Sign in</button>-->
<!--    </div>-->
<!--     /.card-footer -->
<!--</form>-->

<?php if (null == $this->identity()) {?>

    <div class="col-md-offset-4 col-md-4">
        <form class="form-signin" method="post">
            <h2 class="form-signin-heading">Registration</h2>

            <?= $this->formLabel($form->get('full_name')); ?>
            <?= $this->formElement($form->get('full_name')); ?> <br>

            <?= $this->formLabel($form->get('email')); ?>
            <?= $this->formElement($form->get('email')); ?> <br>

            <?= $this->formLabel($form->get('password')); ?>
            <?= $this->formElement($form->get('password')); ?><br>


            <?= $this->formLabel($form->get('confirm_password')); ?>
            <?= $this->formElement($form->get('confirm_password')); ?><br>

            <br><?= $recaptcha->getHTML(); ?><br>
            <?= $this->formElement($form->get('csrf')) ?>
            <button class="btn btn-lg btn-primary btn-block" type="submit">Registration</button>
        </form>
    </div>
<?php } else { ?>
    <p> Ви вже зареєстровані!</p>
<?php } ?>