<div class="row d-flex p-3" >

<?php require_once 'menu.php'; ?>

    <!-- Profle Content -->
    <div class="col-lg-9" >
        <div class="card border-primary mb-3">
            <div class="card-header bg-transparent border-success">
                Нижче наведено ім’я, адреса електронної пошти, контакти та інше, що зберігається у вашому обліковому записі.</div>
            <div class="card-body text-dark">
                <table class="table">
                    <thead>
                    <h3 class="card-title-light">Ваші дані</h3>
                    </thead>
                    <tbody>
                    <tr> <td>Ваш ID: </td> <td><?= $user->getId()?></td> </tr>
                    <tr> <td>Імя: </td> <td><?= $user->getFullName()?></td> </tr>
                    <tr> <td>Email: </td> <td><?= $user->getEmail()?></td> </tr>
                    <tr> <td>Дата Реєстрації: </td> <td><?= $user->getDateCreated()?></td> </tr>
                    <tr> <td>Дата останього оновлення профілю: </td> <td><?= $user->getDateUpdated()?></td> </tr>
                    <tr> <td>Ваші ролі на сайті: </td> <td><?= $user->getRolesAsString()?></td> </tr>
                    </tr>
                    </tbody>
                </table>
            </div>
            <div class="card-footer bg-transparent border-success">
                <a href="<?=$this->url('profile_settings') ?>">Змінити Інформацію</a>
            </div>
        </div>
    </div>
