<div class="row d-flex p-3" >
<?php require_once 'menu.php'; ?>

<!-- Profle Content -->
<div class="col-lg-9" >
    <!-- Nav tabs -->
    <div class="row " >
        <ul class="nav nav-tabs">
            <li class="nav-item">
                <a class="nav-link active" data-toggle="tab" href="#nav-edit" role="tab">Edit Profile</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#nav-security" role="tab">Security Settings</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#nav-notification" role="tab">Notification Settings</a>
            </li>
        </ul>
    </div>

    <!-- Tab panes -->
    <div id="nav" class="tab-content d-flex p-3">
        <!-- Edit Profile -->
        <div class="tab-pane fade show active" id="nav-edit" role="tabpanel" data-parent="#nav">
            <h2 class="h4 g-font-weight-300">Manage your Name, ID and Email Addresses</h2>
            <p>Below are name, email addresse, contacts and more on file for your account.</p>

            <ul class="list-unstyled g-mb-30">
                <!-- Name -->
                <li class="d-flex align-items-center justify-content-between g-brd-bottom g-brd-gray-light-v4 g-py-15">
                    <div class="g-pr-10">
                        <strong class="d-block d-md-inline-block g-color-gray-dark-v2 g-width-200 g-pr-10">Name</strong>
                        <span class="align-top">John Doe</span>
                    </div>
                    <span>
                        <i class="icon-pencil g-color-gray-dark-v5 g-color-primary--hover g-cursor-pointer g-pos-rel g-top-1"></i>
                      </span>
                </li>
                <!-- End Name -->

                <!-- Your ID -->
                <li class="d-flex align-items-center justify-content-between g-brd-bottom g-brd-gray-light-v4 g-py-15">
                    <div class="g-pr-10">
                        <strong class="d-block d-md-inline-block g-color-gray-dark-v2 g-width-200 g-pr-10">Your ID</strong>
                        <span class="align-top">FKJ-032440</span>
                    </div>
                    <span>
                        <i class="icon-pencil g-color-gray-dark-v5 g-color-primary--hover g-cursor-pointer g-pos-rel g-top-1"></i>
                      </span>
                </li>
                <!-- End Your ID -->

                <!-- Company Name -->
                <li class="d-flex align-items-center justify-content-between g-brd-bottom g-brd-gray-light-v4 g-py-15">
                    <div class="g-pr-10">
                        <strong class="d-block d-md-inline-block g-color-gray-dark-v2 g-width-200 g-pr-10">Company name</strong>
                        <span class="align-top">Htmlstream</span>
                    </div>
                    <span>
                        <i class="icon-pencil g-color-gray-dark-v5 g-color-primary--hover g-cursor-pointer g-pos-rel g-top-1"></i>
                      </span>
                </li>
                <!-- End Company Name -->

                <!-- Position -->
                <li class="d-flex align-items-center justify-content-between g-brd-bottom g-brd-gray-light-v4 g-py-15">
                    <div class="g-pr-10">
                        <strong class="d-block d-md-inline-block g-color-gray-dark-v2 g-width-200 g-pr-10">Position</strong>
                        <span class="align-top">Project Manager</span>
                    </div>
                    <span>
                        <i class="icon-pencil g-color-gray-dark-v5 g-color-primary--hover g-cursor-pointer g-pos-rel g-top-1"></i>
                      </span>
                </li>
                <!-- End Position -->

                <!-- Primary Email Address -->
                <li class="d-flex align-items-center justify-content-between g-brd-bottom g-brd-gray-light-v4 g-py-15">
                    <div class="g-pr-10">
                        <strong class="d-block d-md-inline-block g-color-gray-dark-v2 g-width-200 g-pr-10">Primary email address</strong>
                        <span class="align-top">john.doe@htmlstream.com</span>
                    </div>
                    <span>
                        <i class="icon-pencil g-color-gray-dark-v5 g-color-primary--hover g-cursor-pointer g-pos-rel g-top-1"></i>
                      </span>
                </li>
                <!-- End Primary Email Address -->

                <!-- Linked Account -->
                <li class="d-flex align-items-center justify-content-between g-brd-bottom g-brd-gray-light-v4 g-py-15">
                    <div class="g-pr-10">
                        <strong class="d-block d-md-inline-block g-color-gray-dark-v2 g-width-200 g-pr-10">Linked account</strong>
                        <span class="align-top">Facebook</span>
                    </div>
                    <span>
                        <i class="icon-pencil g-color-gray-dark-v5 g-color-primary--hover g-cursor-pointer g-pos-rel g-top-1"></i>
                      </span>
                </li>
                <!-- End Linked Account -->

                <!-- Website -->
                <li class="d-flex align-items-center justify-content-between g-brd-bottom g-brd-gray-light-v4 g-py-15">
                    <div class="g-pr-10">
                        <strong class="d-block d-md-inline-block g-color-gray-dark-v2 g-width-200 g-pr-10">Website</strong>
                        <span class="align-top">https://htmlstream.com</span>
                    </div>
                    <span>
                        <i class="icon-pencil g-color-gray-dark-v5 g-color-primary--hover g-cursor-pointer g-pos-rel g-top-1"></i>
                      </span>
                </li>
                <!-- End Website -->

                <!-- Phone Number -->
                <li class="d-flex align-items-center justify-content-between g-brd-bottom g-brd-gray-light-v4 g-py-15">
                    <div class="g-pr-10">
                        <strong class="d-block d-md-inline-block g-color-gray-dark-v2 g-width-200 g-pr-10">Phone number</strong>
                        <span class="align-top">(+123) 456 7890</span>
                    </div>
                    <span>
                        <i class="icon-pencil g-color-gray-dark-v5 g-color-primary--hover g-cursor-pointer g-pos-rel g-top-1"></i>
                      </span>
                </li>
                <!-- End Phone Number -->

                <!-- Office Number -->
                <li class="d-flex align-items-center justify-content-between g-brd-bottom g-brd-gray-light-v4 g-py-15">
                    <div class="g-pr-10">
                        <strong class="d-block d-md-inline-block g-color-gray-dark-v2 g-width-200 g-pr-10">Office number</strong>
                        <span class="align-top">(+123) 456 7891</span>
                    </div>
                    <span>
                        <i class="icon-pencil g-color-gray-dark-v5 g-color-primary--hover g-cursor-pointer g-pos-rel g-top-1"></i>
                      </span>
                </li>
                <!-- End Office Number -->

                <!-- Address -->
                <li class="d-flex align-items-center justify-content-between g-brd-bottom g-brd-gray-light-v4 g-py-15">
                    <div class="g-pr-10">
                        <strong class="d-block d-md-inline-block g-color-gray-dark-v2 g-width-200 g-pr-10">Address</strong>
                        <span class="align-top">795 Folsom Ave, Suite 600, San Francisco CA, US </span>
                    </div>
                    <span>
                        <i class="icon-pencil g-color-gray-dark-v5 g-color-primary--hover g-cursor-pointer g-pos-rel g-top-1"></i>
                      </span>
                </li>
                <!-- End Address -->
            </ul>

            <div class="text-sm-right">
                <a class="btn u-btn-darkgray rounded-0 g-py-12 g-px-25 g-mr-10" href="#">Cancel</a>
                <a class="btn u-btn-primary rounded-0 g-py-12 g-px-25" href="#">Save Changes</a>
            </div>
        </div>
        <!-- End Edit Profile -->

        <!-- Security Settings -->
        <div class="tab-pane fade" id="nav-security" role="tabpanel" data-parent="#nav">
            <h2 class="h4 g-font-weight-300">Security Settings</h2>
            <p class="g-mb-25">Reset your password, change verifications and so on.</p>

            <form>
                <!-- Current Password -->
                <div class="form-group row g-mb-25">
                    <label class="col-sm-3 col-form-label g-color-gray-dark-v2 g-font-weight-700 text-sm-right g-mb-10">Current password</label>
                    <div class="col-sm-9">
                        <div class="input-group g-brd-primary--focus">
                            <input class="form-control form-control-md border-right-0 rounded-0 g-py-13 pr-0" type="password" placeholder="Current password">
                            <div class="input-group-append">
                                <span class="input-group-text g-bg-white g-color-gray-light-v1 rounded-0"><i class="icon-lock"></i></span>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- End Current Password -->

                <!-- New Password -->
                <div class="form-group row g-mb-25">
                    <label class="col-sm-3 col-form-label g-color-gray-dark-v2 g-font-weight-700 text-sm-right g-mb-10">New password</label>
                    <div class="col-sm-9">
                        <div class="input-group g-brd-primary--focus">
                            <input class="form-control form-control-md border-right-0 rounded-0 g-py-13 pr-0" type="password" placeholder="New password">
                            <div class="input-group-append">
                                <span class="input-group-text g-bg-white g-color-gray-light-v1 rounded-0"><i class="icon-lock"></i></span>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- End New Password -->

                <!-- Verify Password -->
                <div class="form-group row g-mb-25">
                    <label class="col-sm-3 col-form-label g-color-gray-dark-v2 g-font-weight-700 text-sm-right g-mb-10">Verify password</label>
                    <div class="col-sm-9">
                        <div class="input-group g-brd-primary--focus">
                            <input class="form-control form-control-md border-right-0 rounded-0 g-py-13 pr-0" type="password" placeholder="Verify password">
                            <div class="input-group-append">
                                <span class="input-group-text g-bg-white g-color-gray-light-v1 rounded-0"><i class="icon-lock"></i></span>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- End Verify Password -->

                <!-- Login Verification -->
                <div class="form-group row g-mb-25">
                    <label class="col-sm-3 col-form-label g-color-gray-dark-v2 g-font-weight-700 text-sm-right g-mb-10">Login verification</label>
                    <div class="col-sm-9">
                        <label class="form-check-inline u-check g-pl-25">
                            <input class="g-hidden-xs-up g-pos-abs g-top-0 g-left-0" type="checkbox">
                            <div class="u-check-icon-checkbox-v4 g-absolute-centered--y g-left-0">
                                <i class="fa" data-check-icon=""></i>
                            </div>
                            Verify login requests
                        </label>
                        <small class="d-block text-muted">You need to add a phone to your profile account to enable this feature.</small>
                    </div>
                </div>
                <!-- End Login Verification -->

                <!-- Password Reset -->
                <div class="form-group row g-mb-25">
                    <label class="col-sm-3 col-form-label g-color-gray-dark-v2 g-font-weight-700 text-sm-right g-mb-10">Password reset</label>
                    <div class="col-sm-9">
                        <label class="form-check-inline u-check g-pl-25">
                            <input class="g-hidden-xs-up g-pos-abs g-top-0 g-left-0" type="checkbox">
                            <div class="u-check-icon-checkbox-v4 g-absolute-centered--y g-left-0">
                                <i class="fa" data-check-icon=""></i>
                            </div>
                            Require personal information to reset my password
                        </label>
                        <small class="d-block text-muted">When you check this box, you will be required to verify additional information before you can request a password reset with just your email address.</small>
                    </div>
                </div>
                <!-- End Password Reset -->

                <!-- Save Password -->
                <div class="form-group row g-mb-25">
                    <label class="col-sm-3 col-form-label g-color-gray-dark-v2 g-font-weight-700 text-sm-right g-mb-10">Save password</label>
                    <div class="col-sm-9">
                        <label class="form-check-inline u-check mx-0">
                            <input class="g-hidden-xs-up g-pos-abs g-top-0 g-right-0" name="savePassword" type="checkbox">
                            <div class="u-check-icon-radio-v7">
                                <i class="d-inline-block"></i>
                            </div>
                        </label>
                        <small class="d-block text-muted">When you check this box, you will be saved automatically login to your profile account. Also, you will be always logged in all our services.</small>
                    </div>
                </div>
                <!-- End Save Password -->

                <hr class="g-brd-gray-light-v4 g-my-25">

                <div class="text-sm-right">
                    <a class="btn u-btn-darkgray rounded-0 g-py-12 g-px-25 g-mr-10" href="#">Cancel</a>
                    <a class="btn u-btn-primary rounded-0 g-py-12 g-px-25" href="#">Save Changes</a>
                </div>
            </form>
        </div>
        <!-- End Security Settings -->

        <!-- Notification Settings -->
        <div class="tab-pane fade" id="nav-notification" role="tabpanel" data-parent="#nav">
            <h2 class="h4 g-font-weight-300">Manage your Notifications</h2>
            <p class="g-mb-25">Below are the notifications you may manage.</p>

            <form>
                <!-- Email Notification -->
                <div class="form-group">
                    <label class="d-flex align-items-center justify-content-between">
                        <span>Email notification</span>
                        <div class="u-check">
                            <input class="g-hidden-xs-up g-pos-abs g-top-0 g-right-0" name="emailNotification" type="checkbox" checked="">
                            <div class="u-check-icon-radio-v7">
                                <i class="d-inline-block"></i>
                            </div>
                        </div>
                    </label>
                </div>
                <!-- End Email Notification -->

                <hr class="g-brd-gray-light-v4 g-my-20">

                <!-- Comments Notification -->
                <div class="form-group">
                    <label class="d-flex align-items-center justify-content-between">
                        <span>Send me email notification when a user comments on my blog</span>
                        <div class="u-check">
                            <input class="g-hidden-xs-up g-pos-abs g-top-0 g-right-0" name="commentNotification" type="checkbox">
                            <div class="u-check-icon-radio-v7">
                                <i class="d-inline-block"></i>
                            </div>
                        </div>
                    </label>
                </div>
                <!-- End Comments Notification -->

                <hr class="g-brd-gray-light-v4 g-my-20">

                <!-- Update Notification -->
                <div class="form-group">
                    <label class="d-flex align-items-center justify-content-between">
                        <span>Send me email notification for the latest update</span>
                        <div class="u-check">
                            <input class="g-hidden-xs-up g-pos-abs g-top-0 g-right-0" name="updateNotification" type="checkbox" checked="">
                            <div class="u-check-icon-radio-v7">
                                <i class="d-inline-block"></i>
                            </div>
                        </div>
                    </label>
                </div>
                <!-- End Update Notification -->

                <hr class="g-brd-gray-light-v4 g-my-25">

                <!-- Message Notification -->
                <div class="form-group">
                    <label class="d-flex align-items-center justify-content-between">
                        <span>Send me email notification when a user sends me message</span>
                        <div class="u-check">
                            <input class="g-hidden-xs-up g-pos-abs g-top-0 g-right-0" name="messageNotification" type="checkbox" checked="">
                            <div class="u-check-icon-radio-v7">
                                <i class="d-inline-block"></i>
                            </div>
                        </div>
                    </label>
                </div>
                <!-- End Message Notification -->

                <hr class="g-brd-gray-light-v4 g-my-25">

                <!-- Newsletter Notification -->
                <div class="form-group">
                    <label class="d-flex align-items-center justify-content-between">
                        <span>Receive our monthly newsletter</span>
                        <div class="u-check">
                            <input class="g-hidden-xs-up g-pos-abs g-top-0 g-right-0" name="newsletterNotification" type="checkbox">
                            <div class="u-check-icon-radio-v7">
                                <i class="d-inline-block"></i>
                            </div>
                        </div>
                    </label>
                </div>
                <!-- End Newsletter Notification -->

                <hr class="g-brd-gray-light-v4 g-my-25">

                <div class="text-sm-right">
                    <a class="btn u-btn-darkgray rounded-0 g-py-12 g-px-25 g-mr-10" href="#">Cancel</a>
                    <a class="btn u-btn-primary rounded-0 g-py-12 g-px-25" href="#">Save Changes</a>
                </div>
            </form>
        </div>
        <!-- End Notification Settings -->
    </div>
    <!-- End Tab panes -->
</div>
<!-- End Profle Content -->

</div>
<?php var_dump($profile);?>
