<?php

$changeProfileSettingsForm->get('email')->setAttributes([
    'class'=>'form-control',
    'value' => $user->getEmail()
]);

$changeProfileSettingsForm->get('full_name')->setAttributes([
    'class'=>'form-control',
    'value' => $user->getFullName()
]);

$changeProfileSettingsForm->get('avatar')->setAttributes([
    'class'=>'form-control',
]);

$changeProfileSettingsForm->get('submit')->setAttributes([
        'class' => 'btn btn-primary form-control',
        'value' => 'Зберегти налаштування Профілю'
]);

$changeProfileSettingsForm->prepare();



$changeProfileSecurityForm->get('old_password')->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'Введіть старий пароль'
]);

$changeProfileSecurityForm->get('new_password')->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'Введіть новий пароль'
]);

$changeProfileSecurityForm->get('confirm_new_password')->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'Підтвердіть новий пароль'
]);

$changeProfileSecurityForm->get('submit')->setAttributes([
        'class' => 'btn btn-primary form-control'
]);

$changeProfileSecurityForm->prepare();
?>

<?= $this->flashMessenger()->render('error', ['alert', 'alert-warning']); ?>
<?= $this->flashMessenger()->render('success', ['alert', 'alert-success']); ?>
<?= $this->flashMessenger()->render('info', ['alert', 'alert-info']); ?>

<div class="row d-flex p-3">
    <?php require_once 'menu.php'; ?>
    <!-- Profle Content -->
    <div class="col-lg-9">
        <!-- Nav tabs -->
        <div class="row ">
            <ul class="nav nav-tabs">
                <li class="nav-item">
                    <a class="nav-link active" data-toggle="tab" href="#nav-edit" role="tab">Налаштування Профілю</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" data-toggle="tab" href="#nav-security" role="tab">Налаштування Безпеки</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" data-toggle="tab" href="#nav-notification" role="tab">Налаштування Сповіщень</a>
                </li>
            </ul>
        </div>

        <!-- Tab panes -->
        <div id="nav" class="tab-content d-flex p-3">
            <!-- Edit Profile -->
            <div class="tab-pane fade col-sm-12 show active" id="nav-edit" role="tabpanel" data-parent="#nav">
<!--                <h2 class="h4">Manage your Name, ID and Email Addresses</h2>-->
                <p>Керуйте своїм іменем, адресою електронної пошти та аватаром на сайті</p>

                <div class="col-md-12">
                    <div class="card-body">

                        <?= $this->form()->openTag($changeProfileSettingsForm); ?>

                        <div class="row form-group">
                            <div class="col-sm-4">
                                <?= $this->formLabel($changeProfileSettingsForm->get('email')); ?>
                            </div>
                            <div class="col-sm-8">
                                <div class="input-group">
                                    <?= $this->formElement($changeProfileSettingsForm->get('email')); ?>
                                    <div class="input-group-append">
                                        <span class="input-group-text"><i class="icon-lock"></i></span>
                                    </div>
                                </div>
                                <?= $this->formElementErrors($changeProfileSettingsForm->get('email')); ?>
                            </div>
                        </div>

                        <div class="row form-group">
                            <div class="col-sm-4">
                                <?= $this->formLabel($changeProfileSettingsForm->get('full_name')); ?>
                            </div>
                            <div class="col-sm-8">
                                <div class="input-group">
                                    <?= $this->formElement($changeProfileSettingsForm->get('full_name')); ?>
                                    <div class="input-group-append">
                                        <span class="input-group-text"><i class="icon-lock"></i></span>
                                    </div>
                                </div>
                                <?= $this->formElementErrors($changeProfileSettingsForm->get('full_name')); ?>
                            </div>
                        </div>

                        <div class="row form-group">
                            <div class="col-sm-4">
                                <?= $this->formLabel($changeProfileSettingsForm->get('avatar')); ?>
                            </div>
                            <div class="col-sm-8">
                                <?= $this->formElement($changeProfileSettingsForm->get('avatar')); ?>
                                <?= $this->formElementErrors($changeProfileSettingsForm->get('avatar')); ?>
                            </div>
                        </div>
<!--                        <div class="custom-file">-->
<!--                            <input type="file" class="custom-file-input" id="customFile">-->
<!--                            <label class="custom-file-label" for="customFile">Choose file</label>-->
<!--                        </div>-->
                        <?= $this->formElement($changeProfileSettingsForm->get('csrf')); ?>
                        <?= $this->formElementErrors($changeProfileSettingsForm->get('csrf')); ?>

                        <?= $this->formElement($changeProfileSettingsForm->get('submit')); ?>

                        <?= $this->form()->closeTag(); ?>
                    </div>
                </div>
            </div>
            <!-- End Edit Profile -->

            <!-- Security Settings -->
            <div class="tab-pane fade col-sm-12" id="nav-security" role="tabpanel" data-parent="#nav">
<!--                <h2 class="h4">Налаштування безпеки</h2>-->
                <p>Скиньте пароль, змініть підтвердження тощо.</p>
                <div class="col-md-12">
                    <div class="card-body">

                        <?= $this->form()->openTag($changeProfileSecurityForm); ?>

                        <div class="row form-group">
                            <div class="col-sm-3">
                                <?= $this->formLabel($changeProfileSecurityForm->get('old_password')); ?>
                            </div>
                            <div class="col-sm-9">
                                <div class="input-group">
                                    <?= $this->formElement($changeProfileSecurityForm->get('old_password')); ?>
                                    <div class="input-group-append">
                                        <span class="input-group-text"><i class="icon-lock"></i></span>
                                    </div>
                                </div>
                                <?= $this->formElementErrors($changeProfileSecurityForm->get('old_password')); ?>
                            </div>
                        </div>

                        <div class="row form-group">
                            <div class="col-sm-3">
                                <?= $this->formLabel($changeProfileSecurityForm->get('new_password')); ?>
                            </div>
                            <div class="col-sm-9">
                                <div class="input-group">
                                    <?= $this->formElement($changeProfileSecurityForm->get('new_password')); ?>
                                    <div class="input-group-append">
                                        <span class="input-group-text"><i class="icon-lock"></i></span>
                                    </div>
                                </div>
                                <?= $this->formElementErrors($changeProfileSecurityForm->get('new_password')); ?>
                            </div>
                        </div>

                        <div class="row form-group">
                            <div class="col-sm-3">
                                <?= $this->formLabel($changeProfileSecurityForm->get('confirm_new_password')); ?>
                            </div>
                            <div class="col-sm-9">
                                <div class="input-group">
                                    <?= $this->formElement($changeProfileSecurityForm->get('confirm_new_password')); ?>
                                    <div class="input-group-append">
                                        <span class="input-group-text"><i class="icon-lock"></i></span>
                                    </div>
                                </div>
                                <?= $this->formElementErrors($changeProfileSecurityForm->get('confirm_new_password')); ?>
                            </div>
                        </div>
                        <?= $this->formElement($changeProfileSecurityForm->get('csrf')); ?>
                        <?= $this->formElementErrors($changeProfileSecurityForm->get('csrf')); ?>
                        <input type="hidden" name="type-form" value="change-password">

                        <?= $this->formElement($changeProfileSecurityForm->get('submit')); ?>

                        <?= $this->form()->closeTag(); ?>
                    </div>
                </div>
            </div>
                <!-- End Security Settings -->

                <!-- Notification Settings -->
                <div class="tab-pane fade col-sm-12" id="nav-notification" role="tabpanel" data-parent="#nav">
                    <p>Розділ не працює</p>
                    <h2 class="h4 g-font-weight-300">Керуйте своїми сповіщеннями</h2>
                    <p class="g-mb-25">Нижче наведено сповіщення, якими ви можете керувати.</p>

                    <form>
                        <!-- Email Notification -->
                        <div class="form-group">
                            <label class="d-flex align-items-center justify-content-between">
                                <span>Повідомлення електронною поштою</span>
                                <div class="u-check">
                                    <input class="g-hidden-xs-up g-pos-abs g-top-0 g-right-0" name="emailNotification"
                                           type="checkbox" checked="">
                                    <div class="u-check-icon-radio-v7">
                                        <i class="d-inline-block"></i>
                                    </div>
                                </div>
                            </label>
                        </div>
                        <!-- End Email Notification -->

                        <hr class="g-brd-gray-light-v4 g-my-20">


                        <div class="text-sm-right">
                            <a class="btn btn-primary" href="#">Зберегти зміни</a>
                        </div>
                    </form>
                </div>
                <!-- End Notification Settings -->
            </div>
            <!-- End Tab panes -->
        </div>
        <!-- End Profle Content -->

    </div>
<!--    --><?php //var_dump($user); ?>
