<?php
$this->headTitle('Edit Tag');

$form->get('post-category-name')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'Enter name'
    ]);
$form->get('post-category-description')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'Enter name'
    ]);
$form->get('post-category-status')->setAttributes([
    'class'=>'form-control',
    ]);

$form->get('submit')
        ->setAttributes(['class'=>'btn btn-primary form-control'])
        ->setValue('Update ');

$form->prepare();
?>
<div class="col-md-12">
    <h2>Edit Role <?= $this->escapeHtml($postCategory->getCategoryName()) ?></h2>
</div>
<div class="col-md-9">
    <div class="card card-info">
        <div class="card-header">
            <h3 class="card-title">Please fill out the following form and click the <i>Update</i> button.</h3>
        </div>
        <div class="card-body">
            <?= $this->form()->openTag($form); ?>

            <?= $this->formLabel($form->get('post-category-name')); ?>
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text"><i class="fas fa-user"></i></span>
                </div>
                <?= $this->formElement($form->get('post-category-name')); ?>
                <?= $this->formElementErrors($form->get('post-category-name')); ?>
            </div>

            <?= $this->formLabel($form->get('post-category-description')); ?>
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text"><i class="fas fa-user"></i></span>
                </div>
                <?= $this->formElement($form->get('post-category-description')); ?>
                <?= $this->formElementErrors($form->get('post-category-description')); ?>
            </div>

        </div>
        <!-- /.card-body -->
    </div>
</div>
<div class="col-md-3">
    <div class="card card-info">
        <div class="card-header">
            <h3 class="card-title">Settings</h3>
        </div>
        <div class="card-body">
            <?= $this->formLabel($form->get('post-category-status')); ?>
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text"><i class="fas fa-user"></i></span>
                </div>
                <?= $this->formElement($form->get('post-category-status')); ?>
                <?= $this->formElementErrors($form->get('post-category-status')); ?>
            </div>

            <?= $this->formElement($form->get('csrf')); ?>
            <?= $this->formElementErrors($form->get('csrf')); ?>

            <?= $this->formElement($form->get('submit')); ?>

            <?= $this->form()->closeTag(); ?>
        </div>

    </div>
</div>
