<?php
//var_dump($category);

$this->headTitle('Tag');

?>
<?= $this->flashMessenger()->render('error', ['alert', 'alert-warning']); ?>
<?= $this->flashMessenger()->render('success', ['alert', 'alert-success']); ?>
<?= $this->flashMessenger()->render('info', ['alert', 'alert-info']); ?>
<br>


<div class="col-sm-6">
    <h1>Manage Tag</h1>
</div>

<div class="col-sm-6">
    <ol class="breadcrumb float-sm-right">
        <li class="breadcrumb-item"><a href="#">Home</a></li>
        <li class="breadcrumb-item active">Manage Tag</li>
    </ol>
</div>
<section class="content">
    <p>
        <a class="btn btn-success admin-form-btn admin-form-btn-create" href="<?= $this->url('posts-tags', ['action'=>'add']); ?>">
            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> New Tag
        </a>
    </p>




    <?php if ($tags) { ?>

        <table class="table table-striped">

            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Options</th>
            </tr>

            <?php foreach ($tags as $tag): ?>

                <tr>
                    <td><?= $this->escapeHtml($tag->getId()); ?></td>
                    <td>
                        <a href="<?= $this->url('posts-tags', ['action'=>'view', 'id'=>$tag->getId()]); ?>">
                            <?= $this->escapeHtml($tag->getName()); ?>
                        </a>
                    </td>
                    <td>
                        <a class="btn-sm btn-info admin-form-btn" href="
                        <?= $this->url('posts-tags',['action'=>'edit', 'id'=>$tag->getId()]); ?>">
                            <span class="glyphicon glyphicon-pencil"></span> Edit
                        </a>
                        <?php if($tag->getDateDeleted() == null):?>
                            <a class="btn-sm btn-danger admin-form-btn" href="<?= $this->url('posts-tags',
                                ['action' => 'delete', 'id' => $tag->getId()]); ?>">
                                <span class="glyphicon glyphicon-asterisk"></span> Видалити
                            </a>
                        <?php else:?>
                            <a class="btn-sm btn-secondary admin-form-btn" href="<?= $this->url('posts-tags',
                                ['action' => 'restore', 'id' => $tag->getId()]); ?>">
                                <span class="glyphicon glyphicon-asterisk"></span> Відновити
                            </a>
                        <?php endif; ?>
                    </td>
                </tr>

            <?php endforeach; ?>

        </table>
    <?php } else { ?>
        <?php echo 'Ролей поки що немає' ?>
    <?php } ?>
    <!--    --><?//= $this->paginationControl($users, 'Sliding', 'user/partial/paginator', array('route' => 'users')); ?>
</section>
