<?php
$this->headTitle('Permissions');

//$this->mainMenu()->setActiveItemId('permissions');
//
//$this->pageBreadcrumbs()->setItems([
//            'Home'=>$this->url('home'),
//            'Manage Permissions'=>$this->url('permissions'),
//            ]);
?>

<div class="col-sm-6">
    <h1>Manage Permissions</h1>
</div>
<?= $this->flashMessenger()->render('error', ['alert', 'alert-warning']); ?>
<?= $this->flashMessenger()->render('success', ['alert', 'alert-success']); ?>
<?= $this->flashMessenger()->render('info', ['alert', 'alert-info']); ?>

<div class="col-sm-6">
    <ol class="breadcrumb float-sm-right">
        <li class="breadcrumb-item"><a href="#">Home</a></li>
        <li class="breadcrumb-item active">Manage Permissions</li>
    </ol>
</div>
<section class="content">
    <p>
        <a class="btn btn-success admin-form-btn admin-form-btn-create" href="
        <?= $this->url('permissions', ['action'=>'add']); ?>">
            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> New Permissions
        </a>
    </p>




    <?php if ($permissions) { ?>

        <table class="table table-striped">

            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Description</th>
                <th>Date Created</th>
                <th>Actions</th>
            </tr>

            <?php foreach ($permissions as $permission): ?>

                <tr>
                    <td><?= $this->escapeHtml($permission->getId()); ?></td>
                    <td>
                        <a href="<?= $this->url('roles', ['action'=>'view', 'id'=>$permission->getId()]); ?>">
                            <?= $this->escapeHtml($permission->getName()); ?>
                        </a>
                    </td>
                    <td>
                        <?= $this->escapeHtml($permission->getDescription()); ?></a>
                    </td>
                    <td>
                        <nobr><?= $this->escapeHtml($permission->getDateCreated()); ?></nobr>
                    </td>
                    <td>
                        <a class="btn-sm btn-info admin-form-btn" href="
                        <?= $this->url('permissions', ['action'=>'edit', 'id'=>$permission->getId()]); ?>">
                            <span class="glyphicon glyphicon-pencil"></span> Edit
                        </a>
                        <a class="btn-sm btn-danger admin-form-btn" href="
                        <?= $this->url('permissions',['action'=>'delete', 'id'=>$permission->getId()]); ?>">
                            <span class="glyphicon glyphicon-asterisk"></span> Delete
                        </a>
                    </td>
                </tr>

            <?php endforeach; ?>

        </table>
    <?php } else { ?>
        <?php echo 'Дозволи поки що немає' ?>
    <?php } ?>
    <!--    --><?//= $this->paginationControl($users, 'Sliding', 'user/partial/paginator', array('route' => 'users')); ?>
</section>
