<?php
//$this->headTitle('Users');
//
//$this->mainMenu()->setActiveItemId('users');
//
//$this->pageBreadcrumbs()->setItems([
//    'Home'=>$this->url('home'),
//    'Manage Users'=>$this->url('users'),
//]);
//?>

<div class="col-sm-6">
    <h1>Manage Users</h1>
</div>

<div class="col-sm-6">
    <ol class="breadcrumb float-sm-right">
        <li class="breadcrumb-item"><a href="#">Home</a></li>
        <li class="breadcrumb-item active">Manage Users</li>
    </ol>
</div>
<section class="content">
    <p>
        <a class="btn btn-success admin-form-btn admin-form-btn-create" href="<?= $this->url('users', ['action' => 'add']); ?>">
            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> New User
        </a>
    </p>




    <?php if ($users) { ?>

        <table class="table table-striped">

            <tr>
                <th>ID</th>
                <th>E-mail</th>
                <th>Full Name</th>
                <th>Role(s)</th>
                <th>Date Created</th>
                <th>Status</th>
                <th>Actions</th>
            </tr>

            <?php foreach ($users as $user): ?>

                <tr>
                    <td><?= $this->escapeHtml($user->getId()); ?></td>
                    <td>
                        <a href="<?= $this->url('users', ['action' => 'view', 'id' => $user->getId()]); ?>">
                            <?= $this->escapeHtml($user->getEmail()); ?>
                        </a>
                    </td>
                    <td>
                        <?= $this->escapeHtml($user->getFullName()); ?></a>
                    </td>
                    <td>
                        <?= $this->escapeHtml($user->getRolesAsString()); ?></a>
                    </td>
                    <td>
                        <nobr><?= $this->escapeHtml($user->getDateCreated()); ?></nobr>
                    </td>
                    <td><?= $this->escapeHtml($user->getStatusAsString()); ?></td>
                    <td>
                        <a class="btn-sm btn-info admin-form-btn" href="<?= $this->url('users',
                            ['action' => 'edit', 'id' => $user->getId()]); ?>">
                            <span class="glyphicon glyphicon-pencil"></span> Edit
                        </a>
                        <a class="btn-sm btn-danger admin-form-btn" href="<?= $this->url('users',
                            ['action' => 'change-password', 'id' => $user->getId()]); ?>">
                            <span class="glyphicon glyphicon-asterisk"></span> Change Password
                        </a>
                    </td>
                </tr>

            <?php endforeach; ?>

        </table>
    <?php } else { ?>
        <?php echo 'Користувачів поки що немає' ?>
    <?php } ?>
    <?= $this->paginationControl($users, 'Sliding', 'user/partial/paginator', array('route' => 'users')); ?>
</section>
