<?php
$this->headTitle('Reset Password');

$form->get('email')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'Email address'
    ]);

$form->get('submit')->setAttributes([
    'class'=>'btn btn-large btn-primary'
]);

$form->prepare();
?>
    <div class="col-md-offset-5 col-md-5">
        <?= $this->form()->openTag($form); ?>

        <h2>Reset Password</h2>

        <p>Enter your e-mail address below to reset your password</p>

        <?= $this->formElement($form->get('email')); ?>
        <?= $this->formElementErrors($form->get('email')); ?> <br>

        <?= $recaptcha->getHTML(); ?>

        <?= $this->formElement($form->get('submit')); ?>

        <?= $this->formElement($form->get('csrf')); ?>

        <?= $this->form()->closeTag(); ?>
    </div>