<?php
$this->headTitle("Not Authorized");
?>

<section class="content-wrapper">
    <div class="error-page">
        <h2 class="headline text-warning"> 403</h2>

        <div class="error-content">
            <h3><i class="fas fa-exclamation-triangle text-warning"></i> Oops! You Unauthorized.</h3>

            <p class="alert alert-warning">
                Sorry, you have no permission to see this page.
            </p>

            <form class="search-form">
                <div class="input-group">
                    <a class="btn btn-outline-warning btn-block" href="/login">Login</a>
                </div>
                <!-- /.input-group -->
            </form>
        </div>
        <!-- /.error-content -->
    </div>
    <!-- /.error-page -->
</section>
