<?php
$this->headTitle('View Role');

//$this->mainMenu()->setActiveItemId('roles');
//
//$this->pageBreadcrumbs()->setItems([
//            'Home'=>$this->url('home'),
//            'Manage Roles'=>$this->url('roles'),
//            'View Role ' . $role->getName() => $this->url('roles', ['action'=>'view', 'id'=>$role->getId()])
//            ]);
?>

<?//= $this->flashMessenger()->render('error', ['alert', 'alert-warning']); ?>
<?//= $this->flashMessenger()->render('success', ['alert', 'alert-success']); ?>
<?//= $this->flashMessenger()->render('info', ['alert', 'alert-info']); ?>

<div class="col-md-12">
    <h2>View Role <b><?= $this->escapeHtml($role->getName()) ?></b></h2>
</div>
<div class="col-md-5">
    <div class="card card-primary card-outline">
        <div class="card-body box-profile">
            <!--            <div class="text-center">-->
            <!--                <img class="profile-user-img img-fluid img-circle" src="../../dist/img/user4-128x128.jpg" alt="User profile picture">-->
            <!--            </div>-->

            <h3 class="profile-username text-center"> ID <?= $this->escapeHtml($role->getId()) ?></h3>

            <p class="text-muted text-center"><?= $this->escapeHtml($role->getName()) ?></p>

            <ul class="list-group list-group-unbordered mb-3">
                <li class="list-group-item">
                    <b>Description</b> <a class="float-right"><?= $this->escapeHtml($role->getDescription()) ?></a>
                </li>
            </ul>
            <ul class="list-group list-group-unbordered mb-3">
                <li class="list-group-item">
                    <b>Date Created</b> <a class="float-right"><?= $this->escapeHtml($role->getDateCreated()) ?></a>
                </li>
            </ul>

            <a href="<?= $this->url('roles', ['action'=>'edit', 'id'=>$role->getId()]); ?>"
               class="btn btn-primary btn-block"><b>Edit <?= $this->escapeHtml($role->getName()) ?></b></a>
        </div>
        <!-- /.card-body -->
    </div>
    <!-- /.card -->
</div>
<div class="col-md-7">
    <!-- About Me Box -->
    <div class="card card-primary">
        <div class="card-header">
            <h3 class="card-title">Permissions</h3>
        </div>
        <!-- /.card-header -->
        <div class="card-body">
            <table class="table table-striped table-bordered">
                <tr>
                    <th>Name</th>   <th>Description</th>
                </tr>
                <?php foreach($allPermissions as $permission): ?>
                    <tr>
                        <td>
                            <input type="checkbox" disabled <?php if (isset($effectivePermissions[$permission->getName()])) echo 'checked'; ?>>
                            <?= $this->escapeHtml($permission->getName()) ?>
                            <?php if (isset($effectivePermissions[$permission->getName()]) && $effectivePermissions[$permission->getName()]=='inherited'): ?>
                                <em>(inherited)</em>
                            <?php endif; ?>
                        </td>
                        <td><?= $this->escapeHtml($permission->getDescription()) ?></td>
                    </tr>
                <?php endforeach; ?>
            </table>
            <hr>
            <a href="<?= $this->url('roles', ['action'=>'editPermissions', 'id'=>$role->getId()]) ?>"
               class="btn btn-primary btn-block"><b>Edit Permissions</b></a>
        </div>
        <!-- /.card-body -->
    </div>
    <!-- /.card -->
</div>
