<?php
$this->headTitle('Add User');

$form->get('author_id')->setAttributes([
    'class'=>'form-control',
]);

$form->get('category_id')->setAttributes([
    'class'=>'form-control',
]);

$form->get('title')->setAttributes([
    'class'=>'form-control',
]);

$form->get('content')->setAttributes([
    'class'=>'form-control'
]);

$form->get('description')->setAttributes([
    'class'=>'form-control',
]);

$form->get('image')->setAttributes([
    'class'=>'form-control',
]);

$form->get('tags')->setAttributes([
    'class'=>'form-control'
]);

$form->get('submit')->setAttributes(['class'=>'btn btn-success form-control']);

$form->prepare();
?>
<div class="col-md-12">
    <h2>Add New Post</h2>
</div>
<div class="col-md-9">
    <div class="card card-info">
        <div class="card-header">
            <h3 class="card-title">Please fill out the following form and click the <i>Create</i> button.</h3>
        </div>
        <div class="card-body">
            <?= $this->form()->openTag($form); ?>

            <?= $this->formLabel($form->get('title')); ?>
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text"><i class="fas fa-pen-fancy"></i></span>
                </div>
                <?= $this->formElement($form->get('title')); ?>
                <?= $this->formElementErrors($form->get('title')); ?>
            </div>

            <?= $this->formLabel($form->get('content')); ?>
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text"><i class="fas fa-pen-fancy"></i></span>
                </div>
                <?= $this->formElement($form->get('content')); ?>
                <?= $this->formElementErrors($form->get('content')); ?>
            </div>

            <?= $this->formLabel($form->get('description')); ?>
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text"><i class="fas fa-pen-fancy"></i></span>
                </div>
                <?= $this->formElement($form->get('description')); ?>
                <?= $this->formElementErrors($form->get('description')); ?>
            </div>

            <?= $this->formLabel($form->get('image')); ?>
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text"><i class="fas fa-image"></i></span>
                </div>
                <?= $this->formElement($form->get('image')); ?>
                <?= $this->formElementErrors($form->get('image')); ?>
            </div>


        </div>
        <!-- /.card-body -->
    </div>
</div>
<div class="col-md-3">
    <div class="card card-info">
        <div class="card-header">
            <h3 class="card-title">Settings</h3>
        </div>
        <div class="card-body">

            <?= $this->formLabel($form->get('author_id')); ?>
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text"><i class="fas fa-user"></i></span>
                </div>
                <?= $this->formElement($form->get('author_id')); ?>
                <?= $this->formElementErrors($form->get('author_id')); ?>
            </div>

            <?= $this->formLabel($form->get('category_id')); ?>
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text"><i class="fas fa-user"></i></span>
                </div>
                <?= $this->formElement($form->get('category_id')); ?>
                <?= $this->formElementErrors($form->get('category_id')); ?>
            </div>

            <?= $this->formLabel($form->get('status')); ?>
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text"><i class="fas fa-eye-slash"></i></span>
                </div>
                <?= $this->formElement($form->get('status')); ?>
                <?= $this->formElementErrors($form->get('status')); ?>
            </div>

            <?= $this->formLabel($form->get('tags')); ?>
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text"><i class="fas fa-tags"></i></span>
                </div>
                <?= $this->formElement($form->get('tags')); ?>
                <?= $this->formElementErrors($form->get('tags')); ?>
            </div>

            <?= $this->formElement($form->get('csrf')); ?>
            <?= $this->formElementErrors($form->get('csrf')); ?>

            <?= $this->formElement($form->get('submit')); ?>

            <?= $this->form()->closeTag(); ?>
        </div>
        <!-- /.card-body -->
    </div>
</div>
