<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<?= $this->doctype() ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Laminas MVC Skeleton')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink([
                                'rel' => 'shortcut icon',
                                'type' => 'image/vnd.microsoft.icon',
                                'href' => $this->basePath() . '/img/favicon.ico'
                            ])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
?>

        <!-- Scripts -->
        <?= $this->headScript() ?>
    </head>
    <body>

        <nav class="navbar navbar-expand-lg navbar-dark bg-dark" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button
                        class="navbar-toggler"
                        type="button"
                        data-toggle="collapse"
                        data-target="#navbarSupportedContent"
                        aria-controls="navbarSupportedContent"
                        aria-expanded="false"
                        aria-label="Toggle navigation"
                    >
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <a class="navbar-brand" href="<?= $this->url('home') ?>">
                        <img src="<?= $this->basePath('img/laminas-logo.svg') ?>" alt="Laminas">
                    </a>
                </div>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav">

                        <li class="nav-item <?=$this->url() === '/' ? 'active' : '' ?>">
                            <a class="nav-link" href="<?= $this->url('home') ?>">
                                Home <span class="sr-only">(current)</span>
                            </a>
                        </li>
                        <li class="nav-item <?=$this->url() === '/about' ? 'active' : '' ?>">
                            <a class="nav-link" href="<?= $this->url('about') ?>">
                                About
                            </a>
                        </li>
                        <li class="nav-item <?=$this->url() === '/contact-us' ? 'active' : '' ?>">
                            <a class="nav-link" href="<?= $this->url('contactus') ?>">
                                Contact
                            </a>
                        </li>
                        <li class="nav-item <?=$this->url() === '/reg' ? 'active' : '' ?>">
                            <a class="nav-link" href="<?= $this->url('reg', ['action' => 'index']); ?>">
                                Reg
                            </a>
                        </li>
                    </ul>
                    </div>
                    <ul class="navbar-nav">
                        <li class="dropdown show">
                            <?php if ($this->identity()) { ?>
                            <a class="dropdown-toggle nav-link" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <?= $this->escapeHtml($this->identity()) ?>
                            </a>

                            <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">

                                <a class="dropdown-item" href="<?= $this->url('profile') ?>">
                                    Profile
                                </a>
                                <a class="dropdown-item" href="<?= $this->url('profile', ['action' => 'settings']) ?>">
                                    Settings
                                </a>

                                <?php if ($this->access('role.manage')) { ?>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" href="<?= $this->url('home_user_admin') ?>">
                                        Admin Panel
                                    </a>
                                <?php } ?>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="<?= $this->url('logout') ?>">
                                    Logout
                                </a>
                            </div>

                            <?php } else { ?>
                                <ul class="nav justify-content-center">
                                    <li class="nav-item">
                                        <a class="nav-link" href="<?= $this->url('login') ?>">Login</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" href="<?= $this->url('registration'); ?>">Registration</a>
                                    </li>
                                </ul>
                            <?php } ?>
                        </li>


                    </ul>
            </div>
        </nav>

        <div class="container">
<!--            <div class="row col-md-12">
                     Navigation bar
                    <?php
                    // Check if the activeMenuItemId passed to layout view model
                    // and if so, use it for setting active navbar item.
//                    if (isset($activeMenuItemId)) {
//                        $this->mainMenu()->setActiveItemId($activeMenuItemId);
//                    }

                    // Render the navbar
//                    echo $this->mainMenu()->render();
                    ?>
            </div>

            <div class="row col-md-12">
                     Breadcrumbs
                    <?php //$this->pageBreadcrumbs()->render(); ?>
          </div>-->
            <div class="row">
                <div class="col-md-12">
                    <!-- Page content placeholder -->
                    <?= $this->content; ?>
                </div>
            </div>
            <hr>
            <footer>
                <p>
                    &copy; <?= date('Y') ?>
                    <a href="https://getlaminas.org/">Laminas Project</a> a Series of LF Projects, LLC.
                </p>
            </footer>
        </div>
        <?= $this->inlineScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.5.1.min.js'))
            ->prependFile($this->basePath('js/custom.js')) ?>
    </body>
</html>
