<?php
$this->headTitle('Edit Permission');

//$this->mainMenu()->setActiveItemId('permissions');
//
//$this->pageBreadcrumbs()->setItems([
//            'Home'=>$this->url('home'),
//            'Manage Permissions'=>$this->url('permissions'),
//            'Edit Permission'=>$this->url('permissions', ['action'=>'edit', 'id'=>$permission->getId()])
//            ]);

$form->get('name')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'Enter name'
    ]);

$form->get('description')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'Enter description'
    ]);

$form->get('submit')
        ->setAttributes(['class'=>'btn btn-primary form-control'])
        ->setValue('Save');

$form->prepare();
?>

<div class="col-md-12">
    <h2>Edit Permission <?= $this->escapeHtml($permission->getName()) ?></h2>
</div>
<div class="col-md-9">
    <div class="card card-info">
        <div class="card-header">
            <h3 class="card-title">Please fill out the following form and click the <i>Update</i> button.</h3>
        </div>
        <div class="card-body">
            <?= $this->form()->openTag($form); ?>

            <?= $this->formLabel($form->get('name')); ?>
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text"><i class="fas fa-user"></i></span>
                </div>
                <?= $this->formElement($form->get('name')); ?>
                <?= $this->formElementErrors($form->get('name')); ?>
            </div>

            <?= $this->formLabel($form->get('description')); ?>
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text"><i class="fas fa-user"></i></span>
                </div>
                <?= $this->formElement($form->get('description')); ?>
                <?= $this->formElementErrors($form->get('description')); ?>
            </div>
        </div>
        <!-- /.card-body -->
    </div>
</div>
<div class="col-md-3">
    <div class="card card-info">
        <div class="card-header">
            <h3 class="card-title">Settings</h3>
        </div>
        <div class="card-body">

            <?= $this->formElement($form->get('csrf')); ?>
            <?= $this->formElementErrors($form->get('csrf')); ?>

            <?= $this->formElement($form->get('submit')); ?>

            <?= $this->form()->closeTag(); ?>
        </div>
        <!-- /.card-body -->
    </div>
</div>
