<?php
$this->headTitle('View Permission');

//$this->mainMenu()->setActiveItemId('permissions');
//
//$this->pageBreadcrumbs()->setItems([
//            'Home'=>$this->url('home'),
//            'Manage Permissions'=>$this->url('permissions'),
//            'View Permission'=>$this->url('permissions', ['action'=>'view', 'id'=>$permission->getId()])
//            ]);
?>

<?//= $this->flashMessenger()->render('error', ['alert', 'alert-warning']); ?>
<?//= $this->flashMessenger()->render('success', ['alert', 'alert-success']); ?>
<?//= $this->flashMessenger()->render('info', ['alert', 'alert-info']); ?>

<div class="col-md-12">
    <h2>View Permission <b><?= $this->escapeHtml($permission->getName()) ?></b></h2>
</div>
<div class="col-md-5">
    <div class="card card-primary card-outline">
        <div class="card-body box-profile">
            <!--            <div class="text-center">-->
            <!--                <img class="profile-user-img img-fluid img-circle" src="../../dist/img/user4-128x128.jpg" alt="User profile picture">-->
            <!--            </div>-->

            <h3 class="profile-username text-center"> ID <?= $this->escapeHtml($permission->getId()) ?></h3>

            <ul class="list-group list-group-unbordered mb-3">
                <li class="list-group-item">
                    <b>Description</b> <a class="float-right"><?= $this->escapeHtml($permission->getName()) ?></a>
                </li>
            </ul>
            <ul class="list-group list-group-unbordered mb-3">
                <li class="list-group-item">
                    <b>Description</b> <a class="float-right"><?= $this->escapeHtml($permission->getDescription()) ?></a>
                </li>
            </ul>
            <ul class="list-group list-group-unbordered mb-3">
                <li class="list-group-item">
                    <b>Date Created</b> <a class="float-right"><?= $this->escapeHtml($permission->getDateCreated()) ?></a>
                </li>
            </ul>

            <a href="<?= $this->url('roles', ['action'=>'edit', 'id'=>$permission->getId()]); ?>"
               class="btn btn-primary btn-block"><b>Edit <?= $this->escapeHtml($permission->getName()) ?></b></a>
        </div>
        <!-- /.card-body -->
    </div>
    <!-- /.card -->
</div>