FROM php:7.4-fpm

#RUN a2enmod rewrite \
#    && sed -i 's!/var/www/html!/var/www/public!g' /etc/apache2/sites-available/000-default.conf \
#    && mv /var/www/html /var/www/public

RUN apt-get update && apt-get install -y wget git unzip \
    && pecl install xdebug \
    && docker-php-ext-enable xdebug

## Install Composer
RUN curl -sS https://getcomposer.org/installer \
  | php -- --install-dir=/usr/local/bin --filename=composer

## Install zip libraries and extension
RUN apt-get install --yes git zlib1g-dev libzip-dev \
    && docker-php-ext-install zip

## Install intl library and extension
RUN apt-get install --yes libicu-dev \
    && docker-php-ext-configure intl \
    && docker-php-ext-install intl

RUN apt-get update && apt-get install -y \
        libfreetype6-dev \
        libjpeg62-turbo-dev \
        libpng-dev \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install -j$(nproc) gd

###
## Some laminas/laminas-db supported PDO extensions
###

## MySQL PDO support
RUN apt-get update \
 && apt-get install -y git zlib1g-dev \
 && docker-php-ext-install pdo pdo_mysql mysqli zip

# MongoDB
 RUN pecl install mongodb \
     && docker-php-ext-enable mongodb

## Redis support.  igbinary and libzstd-dev are only needed based on
## redis pecl options
 RUN pecl install igbinary \
     && docker-php-ext-enable igbinary \
     && apt-get install --yes libzstd-dev \
     && pecl install redis \
     && docker-php-ext-enable redis

ADD ./php.ini /usr/local/etc/php/php.ini
USER root

WORKDIR /code

#RUN chmod -R 777 /code/public
#RUN chmod -R 777 data

#RUN chmod 777 data/cache

## PostgreSQL PDO support
# RUN apt-get install --yes libpq-dev \
#     && docker-php-ext-install pdo_pgsql

###
## laminas/laminas-cache supported extensions
###

## APCU
# RUN pecl install apcu \
#     && docker-php-ext-enable apcu

## Memcached
# RUN apt-get install --yes libmemcached-dev \
#     && pecl install memcached \
#     && docker-php-ext-enable memcached

