<h1>Upload a New Image</h1>

<p>
    Пожалуйста, заполните следующую форму и нажмите кнопку <i>Upload</i>.
</p>

<div class="row">
    <div class="col-md-6">
        <?= /** @var \Application\Form\ImageForm $form */
        $this->form()->openTag($form); ?>

        <div class="form-group">
            <?= $this->formLabel($form->get('file')); ?>
            <?= $this->formElement($form->get('file')); ?>
            <?= $this->formElementErrors($form->get('file')); ?>
            <div class="hint">(PNG and JPG formats are allowed)</div>
        </div>

        <?= $this->formElement($form->get('submit')); ?>

        <?= $this->form()->closeTag(); ?>
    </div>
</div>