<?php
//var_dump($category);

$this->headTitle('Category');

?>
<div class="col-sm-12">
<?= $this->flashMessenger()->render('error', ['alert', 'alert-warning']); ?>
<?= $this->flashMessenger()->render('success', ['alert', 'alert-success']); ?>
<?= $this->flashMessenger()->render('info', ['alert', 'alert-info']); ?>
</div>

<div class="col-sm-6">
    <h1>Manage Categories</h1>
</div>

<div class="col-sm-6">
    <ol class="breadcrumb float-sm-right">
        <li class="breadcrumb-item"><a href="#">Home</a></li>
        <li class="breadcrumb-item active">Manage Categories</li>
    </ol>
</div>
<section class="content">
    <p>
        <a class="btn btn-success admin-form-btn admin-form-btn-create" href="<?= $this->url('posts-category', ['action'=>'add']); ?>">
            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> New Category
        </a>
    </p>




    <?php if ($categories) { ?>

        <table class="table table-striped">

            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Description</th>
                <th>Date Created</th>
                <th>Actions</th>
            </tr>

            <?php foreach ($categories as $category): ?>

                <tr>
                    <td><?= $this->escapeHtml($category->getCategoryId()); ?></td>
                    <td>
                        <a href="<?= $this->url('posts-category', ['action'=>'view', 'id'=>$category->getCategoryId()]); ?>">
                            <?= $this->escapeHtml($category->getCategoryName()); ?>
                        </a>
                    </td>
                    <td>
                        <?= $this->escapeHtml($category->getCategoryDescription()); ?></a>
                    </td>
                    <td>
                        <nobr><?= $this->escapeHtml($category->getCategoryDateCreated()); ?></nobr>
                    </td>
                    <td>
                        <a class="btn-sm btn-info admin-form-btn" href="
                        <?= $this->url('posts-category',['action'=>'edit', 'id'=>$category->getCategoryId()]); ?>">
                            <span class="glyphicon glyphicon-pencil"></span> Edit
                        </a>
                        <?php if($category->getCategoryDateDeleted() == null):?>
                            <a class="btn-sm btn-danger admin-form-btn" href="<?= $this->url('posts-category',
                                ['action' => 'delete', 'id' => $category->getCategoryId()]); ?>">
                                <span class="glyphicon glyphicon-asterisk"></span> Видалити
                            </a>
                        <?php else:?>
                            <a class="btn-sm btn-secondary admin-form-btn" href="<?= $this->url('posts-category',
                                ['action' => 'restore', 'id' => $category->getCategoryId()]); ?>">
                                <span class="glyphicon glyphicon-asterisk"></span> Відновити
                            </a>
                        <?php endif; ?>
                    </td>
                </tr>

            <?php endforeach; ?>

        </table>
    <?php } else { ?>
        <?php echo 'Ролей поки що немає' ?>
    <?php } ?>
    <!--    --><?//= $this->paginationControl($users, 'Sliding', 'user/partial/paginator', array('route' => 'users')); ?>
</section>
