<?php
$this->headTitle('View Tag');

?>
<div class="col-md-12">
    <h2>View Role <b><?= $this->escapeHtml($postCategory->getCategoryName()) ?></b></h2>
</div>
<div class="col-md-5">
    <div class="card card-primary card-outline">
        <div class="card-body box-profile">

            <h3 class="profile-username text-center"> ID <?= $this->escapeHtml($postCategory->getCategoryId()) ?></h3>

            <p class="text-muted text-center"><?= $this->escapeHtml($postCategory->getCategoryName()) ?></p>

            <ul class="list-group list-group-unbordered mb-3">
                <li class="list-group-item">
                    <b>Description</b> <a class="float-right"><?= $this->escapeHtml($postCategory->getCategoryDescription()) ?></a>
                </li>
            </ul>

            <a href="<?= $this->url('posts-category', ['action'=>'edit', 'id'=>$postCategory->getCategoryId()]); ?>"
               class="btn btn-primary btn-block"><b>Edit <?= $this->escapeHtml($postCategory->getCategoryName()) ?></b></a>
        </div>
        <!-- /.card-body -->
    </div>
    <!-- /.card -->
</div>
<div class="col-md-7">

</div>
