<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */

$this->headTitle($meta['title']);
?>
<div class="jumbotron">
    <h1 class="display-4">Welcome to  <?=$appName ?></h1>

    <p>
        Congratulations! You have successfully installed the
        <a href="https://github.com/laminas/laminas-mvc-skeleton" target="_blank">Laminas MVC Skeleton</a>.
        This skeleton can serve as a simple starting point for you to begin
        building your application on Laminas MVC.
    </p>
</div>

<div class="card-deck">
    <div class="card">
        <h2 class="card-header">About</h2>
        <div class="card-body">
            <p>
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Alias deleniti distinctio, ducimus obcaecati porro praesentium sed suscipit. Accusamus aperiam assumenda commodi cupiditate doloribus id non provident quae recusandae repellat sunt temporibus, tenetur ut, voluptatibus voluptatum! Beatae eos eum facilis fuga, maiores minus! Aperiam assumenda autem consequuntur culpa cupiditate deleniti deserunt dignissimos dolor dolorem ducimus fuga fugiat incidunt, ipsam maiores nam nobis odio odit officia, pariatur porro quaerat quas qui quo reiciendis repudiandae ut veniam? Amet animi dicta dolor error facere hic iusto labore maiores, maxime minima nam nesciunt obcaecati officia provident, qui quia quisquam, rem repellat saepe sint sunt unde.
            </p>

            <a class="btn btn-primary" href="https://getlaminas.org/" target="_blank">Laminas Project Portal &raquo;</a>
        </div>
    </div>
</div>
