<?php
/** @var \Application\Form\ContactForm $form */
?>
<h1>Форма зворотнього звязку</h1>

<?= $this->form()->openTag($form);?>
    <div class="form-group">
        <label for="email">
            <?= $this->formLabel($form->get('email'));?>
            <span class="text-danger">*</span>
        </label>
        <?= $this->formElement($form->get('email'));?>
        <?= $this->formElementErrors($form->get('email'));?>

    </div>

    <div class="form-group">
        <label for="phone">
            <?= $this->formLabel($form->get('phone'));?>
        </label>
        <?= $this->formElement($form->get('phone'));?>
        <?= $this->formElementErrors($form->get('phone'));?>
    </div>

    <div class="form-group">
        <label for="subject">
            <?= $this->formLabel($form->get('subject'));?>
            <span class="text-danger">*</span>
        </label>

        <?= $this->formElement($form->get('subject'));?>
        <?= $this->formElementErrors($form->get('subject'));?>
    </div>

    <div class="form-group">
        <label for="body">
            <?= $this->formLabel($form->get('body'));?>
            <span class="text-danger">*</span>
        </label>

        <?= $this->formElement($form->get('body'));?>
        <?= $this->formElementErrors($form->get('body'));?>
    </div>

    <div class="form-group">
        <label for="body">
            <?= $this->formLabel($form->get('file'));?>
        </label>

        <?= $this->formElement($form->get('file'));?>
        <?= $this->formElementErrors($form->get('file'));?>
    </div>

<!--    <div class="form-group inputDnD">-->
<!--        <input type="file"-->
<!--               class="form-control-file text-secondary font-weight-bold"-->
<!--               id="inputFile" onchange="readUrl(this)"-->
<!--               data-title="Drag and drop a file">-->
<!--    </div>-->

<?= $this->formElement($form->get('submit'));?>

<?=  $this->form()->closeTag();?>
