<?php
/** @var \Application\Form\ContactForm $form */
?>
<h1>Форма зворотнього звязку</h1>

<?= $this->form()->openTag($form);?>

    <div class="form-group">
        <?= $this->formLabel($form->get('email'));?>
        <span class="text-danger">*</span>
        <?= $this->formElement($form->get('email'));?>
        <?= $this->formElementErrors($form->get('email'));?>
    </div>

    <div class="form-group">
        <?= $this->formLabel($form->get('phone'));?>
        <?= $this->formElement($form->get('phone'));?>
        <?= $this->formElementErrors($form->get('phone'));?>
    </div>

    <div class="form-group">
        <?= $this->formLabel($form->get('subject'));?>
        <span class="text-danger">*</span>
        <?= $this->formElement($form->get('subject'));?>
        <?= $this->formElementErrors($form->get('subject'));?>
    </div>

    <div class="form-group">
        <?= $this->formLabel($form->get('body'));?>
        <span class="text-danger">*</span>
        <?= $this->formElement($form->get('body'));?>
        <?= $this->formElementErrors($form->get('body'));?>
    </div>

    <div class="form-group inputDnD">
        <?= $this->formLabel($form->get('file'));?>
        <?= $this->formElement($form->get('file'));?>
        <?= $this->formElementErrors($form->get('file'));?>
    </div>

    <br><?= $recaptcha->getHTML(); ?><br>

    <?= $this->formElement($form->get('csrf')); ?>

    <?= $this->formElement($form->get('submit'));?>

<?=  $this->form()->closeTag();?>
